// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhQYnCrtnY9uB7RG4hsoBCP_cy8scUnpM',
    appId: '1:572308154537:web:7ccd414066d9f7d7b3a1b8',
    messagingSenderId: '572308154537',
    projectId: 'spotify-clone-7cf14',
    authDomain: 'spotify-clone-7cf14.firebaseapp.com',
    storageBucket: 'spotify-clone-7cf14.appspot.com',
    measurementId: 'G-6JK7HR4J1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM8Y1hcnV2rv8S3omWWJdChbnvO5Ih5dQ',
    appId: '1:572308154537:android:c623611e1211c0c1b3a1b8',
    messagingSenderId: '572308154537',
    projectId: 'spotify-clone-7cf14',
    storageBucket: 'spotify-clone-7cf14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-zL6IbCkGOQavPuY6j8y3zpqa-CjFUxA',
    appId: '1:572308154537:ios:6ed080f7c4248a03b3a1b8',
    messagingSenderId: '572308154537',
    projectId: 'spotify-clone-7cf14',
    storageBucket: 'spotify-clone-7cf14.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-zL6IbCkGOQavPuY6j8y3zpqa-CjFUxA',
    appId: '1:572308154537:ios:6ed080f7c4248a03b3a1b8',
    messagingSenderId: '572308154537',
    projectId: 'spotify-clone-7cf14',
    storageBucket: 'spotify-clone-7cf14.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhQYnCrtnY9uB7RG4hsoBCP_cy8scUnpM',
    appId: '1:572308154537:web:6f7f0d87c9ec517bb3a1b8',
    messagingSenderId: '572308154537',
    projectId: 'spotify-clone-7cf14',
    authDomain: 'spotify-clone-7cf14.firebaseapp.com',
    storageBucket: 'spotify-clone-7cf14.appspot.com',
    measurementId: 'G-BNF1TZQYRY',
  );
}
